"""Константы проекта."""
MIN_COOKING_TIME = 1
MAX_SMAL_INTEGER_NUM = 32000
MIN_QUANTITY_INGREDIENT = 1
LENGTH_SHORT_CODE = 10

PAGE_SIZE_USERS = 6
PAGE_SIZE_RESIPES = 6
MAX_PAGE_SIZE = 100
MAX_LENGTH_SLAG = 32
MAX_LENGTH_TAG = 32
MAX_LENGTH_NAME_USER = 150
MAX_LENGTH_INGREDIENT = 128
MAX_LENGTH_RECIPE = 256
MAX_LENGTH_USER = 150
MAX_LENGTH_MEASHUREMENT_UNIT = 64
